DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(20) NOT NULL
	, SEXO CHAR(1)
	, IDADE INT
	, CIDADE VARCHAR(20)
    , PRIMARY KEY (IDALUNO)
);

INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('FELIPE', 22, 'M','TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('FRANCO', 28, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PEDRO', 14, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 23, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GUSTAVO', 25, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RICARDO', 26, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCIANO', 38, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('YURI', 12, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUANA', 15, 'F', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EMILI', 17, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('FLAVIA', 20, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LARA', 13, 'F', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('FRANSCISCO', 14, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('BRUNO', 36, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LARA', 11, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CRISTIANE', 34, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUIZA', 18, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('THAIZ', 16, 'F', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MATHEUS', 13, 'M', 'BLUMENAU');

SELECT * FROM ALUNO WHERE SEXO = 'M';
SELECT * FROM ALUNO WHERE IDADE = 19;
SELECT * FROM ALUNO WHERE NOME LIKE 'D%';
SELECT * FROM ALUNO WHERE IDADE BETWEEN 20 AND 22 ;
SELECT * FROM ALUNO WHERE CIDADE IS NULL;
SELECT * FROM ALUNO WHERE CIDADE = 'BLUMENAU';
SELECT * FROM ALUNO WHERE IDADE <>18;
SELECT * FROM ALUNO WHERE NOME LIKE '%RI%';
SELECT * FROM ALUNO WHERE SEXO = 'M' AND IDADE < 20;
SELECT * FROM ALUNO WHERE (SEXO = 'F' AND IDADE > 20) OR (SEXO = 'M' AND IDADE > 17);
SELECT * FROM ALUNO WHERE NOME LIKE "%A%" AND NOME LIKE "%R%";
SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';
SELECT IDALUNO FROM ALUNO WHERE CIDADE = "BLUMENAU";
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE<18;
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE >=15 AND IDADE <= 18 AND CIDADE <> "PALHOCA";
SELECT CIDADE FROM ALUNO WHERE CIDADE <> "NULL"; 
SELECT NOME FROM ALUNO WHERE (IDADE = 18 AND CIDADE = "PALHOCA") OR (IDADE = 17 AND CIDADE = "SAO JOSE");
SELECT NOME FROM ALUNO WHERE SEXO = 'M' AND CIDADE = "TUBARAO" AND IDADE >=18 AND IDADE <= 25;
SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;
SELECT * FROM ALUNO ORDER BY IDADE DESC, NOME ASC; 
SELECT * FROM ALUNO ORDER BY SEXO, NOME;