CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	SEXO ENUM ('M', 'F'),
	IDADE int,
	CIDADE VARCHAR(20)
);

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (1, "FERNANDO", "M", 14, "CHAPECO");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (2, "LUIZ", "M", 18, "ITAJAI");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (3, "BRUNA", "F", 25, "BRUSQUE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (4, "THAIZ", "F", 11, "PALHOCA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (5, "BIANCA", "F", 19, "LAGES");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (6, "PEDRO", "M", 22, "POMERODE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (7, "ALICE", "F", 12, "URUBICI");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (8, "BEATRIZ", "F", 15, "NAVEGANTES");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (9, "LUAN", "M", 26, "URUPEMA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (10, "MARIANA", "F", 19, "ITAPEMA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (11, "FLAVIA", "F", 23, "PENHA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (19, "LAURA", "F", 17, "LAGUNA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (13, "ANDRE", "M", 19, "CURITIBA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (14, "RENAN", "M", 18, "FLORIANOPOLIS");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (15, "YURI", "M", 14, "ITAJAI");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (16, "LARA", "F", 11, "PALHOCA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (17, "CRISTIANE", "F", 29, "URUBICI");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (18, "FRANCISCO", "M", 16, " LAGUNA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (19, "ALYSSA", "F", 11, "TIJUCAS");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (20, "MATHEUS", "M",15, "IMBITUBA");
