 CREATE DATABASE EXE1_18_03;
USE EXE1_18_03;


CREATE TABLE LIVRO(
	CODIGO INT UNIQUE NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(100)
    , EDICAO VARCHAR(60)
    , DT_RESERVA DATE 
    , DT_EMPRESTIMO DATE
    , DT_DEVOLUCAO DATE
    , MATRICULA INT
    , PRIMARY KEY (CODIGO)
);

CREATE TABLE USUARIO(
	MATRICULA INT UNIQUE NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , ENDERECO VARCHAR(100)
    , EMAIL VARCHAR(100)
    , CODIGO_LIVRO INT
    , PRIMARY KEY (MATRICULA)
    , FOREIGN KEY (CODIGO_LIVRO) REFERENCES LIVRO(CODIGO)
);

ALTER TABLE LIVRO
ADD FOREIGN KEY (MATRICULA) REFERENCES USUARIO(MATRICULA);

CREATE TABLE ASSUNTO(
	CODIGO_ASSUNTO INT UNIQUE NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY (CODIGO_ASSUNTO)
);
CREATE TABLE AUTOR(
	CODIGO_AUTOR INT UNIQUE NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , NACIONALIDADE VARCHAR(50)
    , ENDERECO_WEB VARCHAR(200)
    , PRIMARY KEY (CODIGO_AUTOR)
);
CREATE TABLE SUB_ASSUNTO(
	CODIGO_SUBASSUNTO INT UNIQUE NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY(CODIGO_SUBASSUNTO)
);
CREATE TABLE ESCREVER(
	CODIGO_AUTOR INT NOT NULL
    , CODIGO INT NOT NULL
    , PRIMARY KEY (CODIGO, CODIGO_AUTOR)
    , FOREIGN KEY (CODIGO_AUTOR) REFERENCES AUTOR(CODIGO_AUTOR)
    , FOREIGN KEY (CODIGO) REFERENCES LIVRO(CODIGO)
);

CREATE TABLE CONTER(
	CODIGO INT NOT NULL
    , CODIGO_ASSUNTO INT NOT NULL
    , PRIMARY KEY(CODIGO, CODIGO_ASSUNTO)
    , FOREIGN KEY (CODIGO_ASSUNTO) REFERENCES ASSUNTO(CODIGO_ASSUNTO)
    , FOREIGN KEY (CODIGO) REFERENCES LIVRO(CODIGO)
);

CREATE TABLE COMPOSTO(
	CODIGO_SUBASSUNTO INT NOT NULL
    , CODIGO_ASSUNTO INT NOT NULL
    , PRIMARY KEY(CODIGO_SUBASSUNTO, CODIGO_ASSUNTO)
    , FOREIGN KEY (CODIGO_ASSUNTO) REFERENCES ASSUNTO(CODIGO_ASSUNTO)
    , FOREIGN KEY (CODIGO_SUBASSUNTO) REFERENCES SUB_ASSUNTO(CODIGO_SUBASSUNTO)
);